openapi/internal.yaml
package.json
src/adapters/http/application.ts
src/adapters/http/checklist/codec.ts
src/adapters/http/checklist/router.ts
src/domain/checklist/__tests__/preLoadChecklist.test.ts
src/domain/checklist/__tests__/types.test.ts
src/domain/checklist/preLoadChecklist.ts
src/domain/checklist/types.ts
src/main.ts
src/useCases/GetChecklistResultUseCase.ts

- Add checklistreport definition within OpenAPI
- Create an endpoint to get checklistreport
- Add rules useful to check the PreLoad operation requests
Unit tests to check that the rules are working as expected

[VL-27] Add checklistresult endpoint

---

src/useCases/PreLoadUseCase.ts
src/useCases/__tests__/PreLoadUseCase.test.ts

The response of `Request an “upload slot“` endpoint should be something like the following:
```
[
{
"preloadIdx":"1",
"httpMethod":"PUT",
"secret":"b3dd0b61-e22a-4f79-b808-1bb8ea9dae2c",
"url":"http://127.0.0.1:8080/uploadS3/key1",
"key":"key1"
}
]
```
but now the url retuned doesn’t contain the key:
```
[
{
"preloadIdx":"1",
"httpMethod":"PUT",
"secret":"b3dd0b61-e22a-4f79-b808-1bb8ea9dae2c",
"url":"http://127.0.0.1:8080/uploadS3",
"key":"key1"
}
]
```
Unit test

VL-59 Return also the key within the base URL

---

openapi/index.yaml
src/adapters/http/uploadToS3/router.ts
src/domain/UploadToS3RecordRepository.ts
src/useCases/UploadToS3UseCase.ts

Change the endpoint `Upload S3`, the `x-amz-sdk-checksum-algorithm` header parameter is no longer required.
The `x-amz-sdk-checksum-algorithm` header parameter on `Upload S3` endpoint should not be required.

VL-60 Make x-amz-sdk-checksum-algorithm optional

---

docs/architecture/decisions/0003-where-to-publish-container-image.md

Add a new ADR.
We have to choose where to deliver the container image.

VL-56 Add ADR about where to publish container image

---

openapi/index.yaml
src/adapters/http/application.ts
src/adapters/http/checkNotificationStatus/router.ts
src/domain/CheckNotificationStatusRepository.ts
src/domain/__tests__/data.ts
src/domain/types.ts
src/main.ts
src/useCases/CheckNotificationStatusUseCase.ts
src/useCases/__tests__/CheckNotificationStatusUseCase.test.ts
src/useCases/__tests__/PreLoadUseCase.test.ts

Add a new endpoint to emulate the endpoint used to check the status of notification
This endpoint is used to check the status of notification and it must be available
Unit tests

VL-19 Add check notification status endpoint

---

README.md
package.json
src/adapters/http/application.ts
src/adapters/http/createEventStream/router.ts
src/domain/CreateEventStreamRecordRepository.ts
src/domain/__tests__/data.ts
src/main.ts
src/useCases/CreateEventStreamUseCase.ts
src/useCases/__tests__/CreateEventStreamUseCase.test.ts

Add a new endpoint to emulate the endpoint used to create a new event stream
This endpoint is mandatory to check the status of notification of multiple notification at the same time and it must be available

[VL-54] Add create stream endpoint

---

README.md
src/domain/AnyRecord.ts
src/domain/__tests__/data.ts
src/domain/checklist/__tests__/uploadToS3Checklist.test.ts
src/domain/checklist/uploadToS3Checklist.ts
src/main.ts
src/useCases/GetChecklistResultUseCase.ts
src/useCases/__tests__/GetChecklistResultUseCase.test.ts

Add all checks about the endpoint Upload to S3.
Unit tests.

[VL-29] Add checklist about UploadToS3 endpoint

---

src/__tests__/data.ts
src/adapters/http/Handler.ts
src/adapters/http/Problem.ts
src/adapters/http/checklist/codec.ts
src/adapters/inMemory/__tests__/index.test.ts
src/domain/CheckNotificationStatusRepository.ts
src/domain/checklist/__tests__/preLoadChecklist.test.ts
src/domain/checklist/uploadToS3Checklist.ts
src/main.ts
src/useCases/GetChecklistResultUseCase.ts
src/useCases/PreLoadUseCase.ts
src/useCases/SendNotificationUseCase.ts
src/useCases/__tests__/CheckNotificationStatusUseCase.test.ts
src/useCases/__tests__/CreateEventStreamUseCase.test.ts
src/useCases/__tests__/GetChecklistResultUseCase.test.ts
src/useCases/__tests__/PreLoadUseCase.test.ts
tsconfig.json

The compiler is unreliable because we didn't specify to `true` the "compilerOptions.strict" parameter when we started the project.

[VL-85] Enable strict compiler

---

openapi/index.yaml
src/adapters/http/Problem.ts

Add missing parameters on 400 response body.
The OpenAPI is not aligned with the implementation of the system, so the emulator doesn't behave like PN.

[VL-67] - Add timestamp and traceId to error response

---

docs/architecture/decisions/0004-what-formats-to-use-for-git-tag.md
docs/architecture/decisions/0005-how-to-bump-project-version.md

Create new ADRs to define the format of Git tags and the process to follow to bump a project's version.
- Create ADR of Git tag format
- Create ADR for bump process

ADR Git tags format and process to bump version

---

src/adapters/http/uploadToS3/router.ts
src/domain/UploadToS3RecordRepository.ts
src/domain/__tests__/data.ts
src/useCases/UploadToS3UseCase.ts

Use idiomatic code to define optional fields and values.
Replace `io-ts` Option structure with idiomatic code (`?`).

Remove option from type definition and function input

---

src/adapters/http/application.ts
src/adapters/http/consumeEventStream/router.ts
src/domain/CheckNotificationStatusRepository.ts
src/domain/ConsumeEventStreamRecordRepository.ts
src/domain/Database.ts
src/domain/Notification.ts
src/domain/NotificationRequest.ts
src/domain/Snapshot.ts
src/domain/__tests__/data.ts
src/domain/types.ts
src/main.ts
src/useCases/CheckNotificationStatusUseCase.ts
src/useCases/ConsumeEventStreamUseCase.ts
src/useCases/__tests__/CheckNotificationStatusUseCase.test.ts
src/useCases/__tests__/ConsumeEventStreamUseCase.test.ts

Add the endpoint used to consume events from of a stream
This endpoint is mandatory to check the status of notification of multiple notification at the same time and it must be available
Unit tests

[VL-18] Add consume event stream endpoint

---

.npmrc

Create .npmrc file

---

.npmrc

Add tag-version-prefix to `.npmrc` file.

Add tag-version-prefix to npmrc file

---

.github/workflows/main.yaml
README.md

Restore the CI/CD badge. Change the event that triggers the workflow

Fix CI/CD badge

---

src/domain/Notification.ts

Code Review: Small refactor of Notification.ts file

---

.husky/pre-push
openapi/index.yaml
src/adapters/http/application.ts
src/adapters/http/getNotificationDetail/router.ts
src/domain/GetNotificationDetailRepository.ts
src/domain/Notification.ts
src/domain/Snapshot.ts
src/domain/__tests__/data.ts
src/main.ts
src/useCases/CheckNotificationStatusUseCase.ts
src/useCases/ConsumeEventStreamUseCase.ts
src/useCases/GetNotificationDetailUseCase.ts
src/useCases/__tests__/CheckNotificationStatusUseCase.test.ts
src/useCases/__tests__/ConsumeEventStreamUseCase.test.ts
src/useCases/__tests__/GetNotificationDetailUseCase.test.ts

Get details about an accepted notification.
- Add schemas to the OpenAPI specification

[VL-53] Get detail of notification

---

src/domain/checklist/preLoadChecklist.ts

Improve descriptions of preload request checklist

Fixes Preload request checks name

---

openapi/index.yaml

The generated code was broken (some entities was generated as empty objects)

Fix code generation issue due to open-api

---

src/domain/__tests__/data.ts
src/main.ts
src/useCases/SystemEnv.ts

Add missing repositories to the `SystemEnv`

Add missing repositories to SystemEnv

---

src/domain/__tests__/NewNotificationRepository.test.ts

Opt suggestion about #62

---

src/domain/NewNotificationRepository.ts
src/domain/__tests__/NewNotificationRepository.test.ts
src/domain/checklist/sendPaymentNotificationChecklist.ts

Add first part of checks related to the send notification use case

[VL-130] - Add independent checks about send notification

---

src/domain/__tests__/data.ts
src/domain/checklist/__tests__/sendPaymentNotificationChecklist.test.ts
src/domain/checklist/sendPaymentNotificationChecklist.ts

Before this commit, the checks didn't pass if the upload request was one with two elements. After this commit, the check passes
Unit tests

Fix issue on checks about upload slot

---

README.md

Add information about which use cases the system is able to cover and some other information required to use the tool correctly

[VL-126] Add information to the README

---

README.md

Changed the README walk-through.
As a developer, I want to have a simple README file that walks me through the most common scenarios, i.e. running from the source code (yes, I'm on GitHub) or a pre-built docker image (for a super-fast and easy go!). This means also that everything else just falls into more advanced scenarios (such as building a docker image locally).
Starting from this simple consideration, the structure of the README profoundly simplifies leading to this proposed PR.

Rethink the README walk-through

---

.github/workflows/main.yaml

Enable node cache during CI

---

src/domain/PreLoadRepository.ts
src/domain/UploadToS3RecordRepository.ts
src/domain/__tests__/PreLoadRepository.test.ts
src/domain/__tests__/UploadToS3Repository.test.ts
src/domain/__tests__/data.ts
src/domain/checklist/sendPaymentNotificationChecklist.ts

Simplify the code related to checks about UploadToS3 endpoint
Unit tests

Simplify checks about UploadToS3 endpoint

---

src/domain/__tests__/data.ts
src/domain/checks/NewNotificationRequestRecordChecks.ts
src/domain/checks/PreLoadRecordChecks.ts
src/domain/checks/UploadToS3RecordChecks.ts
src/domain/checks/__tests__/NewNotificationRequestRecordChecks.test.ts
src/domain/checks/__tests__/PreLoadRecordChecks.test.ts
src/domain/checks/__tests__/UploadToS3RecordChecks.test.ts
src/domain/checks/__tests__/tcSend01.test.ts
src/domain/checks/report.ts
src/domain/checks/tcSend01bis.ts
src/useCases/GetChecklistResultUseCase.ts

[VL-143] Add checks about use case TC-SEND-01bis

---

src/domain/checks/tcSend01.ts
src/domain/checks/tcSend01bis.ts

Added missing question marks in the JSON output and fix the English
Commitment to quality - Reviewing communication is a continuous process

Put missing question marks and fix the singular

---

src/domain/checks/tcSend01.ts

Added missing question marks in the JSON output for the TC-INVIO-01 use case
Commitment to quality - Reviewing communication is a continuous process

Put missing question marks in the tcSend01 file

---

README.md

I've tried to simplify the steps described in use-cases.
Greater conciseness and simplicity lead to a better understanding

Simplify the use-cases instructions in the README.md file

---

README.md

Add information about TC-SEND-01bis use case.

[VL-146] - Add section about testable use case tc-send-01-bis

---

openapi/index.yaml
src/adapters/http/application.ts
src/adapters/http/getLegalFactDocument/router.ts
src/domain/LegalFactDownloadMetadataRecordRepository.ts
src/domain/__tests__/data.ts
src/main.ts
src/useCases/GetLegalFactDownloadMetadataUseCase.ts
src/useCases/SystemEnv.ts
src/useCases/__tests__/GetLegalFactDownloadMetadataUseCase.test.ts

The emulator should provide the endpoint that allows the legal facts to be downloaded locally. 
Unit tests and manual check.

VL-121 - Add get legal fact metadata endpoint

---

src/domain/CheckNotificationStatusRepository.ts
src/domain/ConsumeEventStreamRecordRepository.ts
src/domain/CreateEventStreamRecordRepository.ts
src/domain/GetNotificationDetailRepository.ts
src/domain/GetNotificationDocumentMetadataRepository.ts
src/domain/GetPaymentNotificationMetadataRecordRepository.ts
src/domain/NewNotificationRepository.ts
src/domain/PreLoadRepository.ts
src/domain/Repository.ts
src/domain/UploadToS3RecordRepository.ts
src/domain/__tests__/data.ts
src/useCases/CheckNotificationStatusUseCase.ts
src/useCases/ConsumeEventStreamUseCase.ts
src/useCases/CreateEventStreamUseCase.ts
src/useCases/GetNotificationDetailUseCase.ts
src/useCases/GetNotificationDocumentMetadataUseCase.ts
src/useCases/GetPaymentNotificationMetadataUseCase.ts
src/useCases/PreLoadUseCase.ts
src/useCases/SendNotificationUseCase.ts
src/useCases/UploadToS3UseCase.ts

Register the timestamp when a request is made.
It's important to know when a request occured so that it will be possible to make some custom logic with that information as well.

[VL-154] - Add timestamps to record

---

README.md

Added the command to pull the latest image from Docker
Explicitly updating docker images within the documented steps helps novice users.

Add the docker instructions to pull the latest image from the registry

---

src/adapters/http/uploadToS3/router.ts
src/domain/UploadToS3RecordRepository.ts
src/domain/__tests__/data.ts
src/domain/checks/UploadToS3RecordChecks.ts
src/useCases/PreLoadUseCase.ts
src/useCases/UploadToS3UseCase.ts
src/useCases/__tests__/PreLoadUseCase.test.ts

Before this PR, there was no check to see if the URL returned by the preload endpoint differed from the one used to upload. Once the PR is merged, the system checks that the two URLs match.
Unit Tests and via pn-b2b-client

VL-133 Change the format of upload endpoint

---

src/domain/ConsumeEventStreamRecordRepository.ts
src/domain/checks/ConsumeEventStreamRecordChecks.ts

Review of tc-send-02 pr

---

README.md
src/domain/ConsumeEventStreamRecordRepository.ts
src/domain/CreateEventStreamRecordRepository.ts
src/domain/Repository.ts
src/domain/__tests__/CreateEventStreamRecordRepository.test.ts
src/domain/__tests__/data.ts
src/domain/checks/ConsumeEventStreamRecordChecks.ts
src/domain/checks/CreateEventStreamRecordChecks.ts
src/domain/checks/__tests__/ConsumeEventStreamRecordChecks.test.ts
src/domain/checks/__tests__/CreateEventStreamRecordChecks.test.ts
src/domain/checks/__tests__/data.ts
src/domain/checks/report.ts
src/domain/checks/tcSend02.ts

Add some checks required in order to satisfy the test case tc-send02.
Added checks:
- verify a stream has been created
- verify that the endpoint to get the events of a stream has been called using the streamId provided by the first endpoint
- verify the accepted event has been received
- verify that an event with a iun populated has been received
Missing checks (that we are going to implements in a future work):
- verify the events successive of the accepted have been received
- verify the endpoints have been called honouring the retry-after
Unit tests
Documentation has been updated in #85

[VL-144] - TC-Send02 checks

---

openapi/index.yaml
src/adapters/http/application.ts
src/adapters/http/getNotificationPrice/router.ts
src/domain/GetNotificationPriceRecordRepository.ts
src/domain/__tests__/data.ts
src/main.ts
src/useCases/GetNotificationPriceUseCase.ts
src/useCases/SystemEnv.ts

Add the endpoint that lists the Event Stream previously created.

VL-166 Add get notification price endpoint

---

src/domain/PreLoadRecord.ts
src/useCases/PreLoadUseCase.ts

Review PR #90

---

src/adapters/http/application.ts
src/adapters/http/download/router.ts
src/domain/DownloadRecord.ts
src/domain/Repository.ts

Create and persists the DownloadRecord, which records every requests coming to the `download` endpoint.
In order to verify if the client makes the request to download a document, we should persist when the request comes.

Create DownloadRecord and persists it

---

README.md

Add the link to the new documentation

Add link to the new documentation

---

src/domain/CreateEventStreamRecord.ts
src/domain/DomainEnv.ts
src/domain/__tests__/data.ts
src/main.ts

Before this commit, the streamId had the same format as a IUN. After this commit, the streamId is a UUID.
Some e2e tests assume that the `streamId` is a UUID, this PR adapts the format of the `streamId` to UUID.

Change the format of streamId

---

src/domain/DomainEnv.ts
src/domain/GetNotificationDetailRecord.ts
src/domain/Notification.ts
src/domain/Snapshot.ts
src/domain/TimelineElement.ts
src/domain/__tests__/data.ts
src/main.ts

A notification should change its state, simulating a status progression.
Before this PR, the notification had the same state. After this PR, the notification state changes after the second time it is viewed (via any endpoint able to return its IUN).
Via e2e tests

[VL-147] Add the timeline constructor

---

src/domain/DomainEnv.ts
src/domain/GetNotificationPriceRecord.ts
src/domain/__tests__/data.ts
src/main.ts

Change value of the notification price to 100.

[VL-176] - Move notification price to env and change default value

---

src/domain/checks/tcSend01.ts

On tcSend01, there was a check called two times (and it was wrong).
Now, the check is invoked properly

Invoke right check

---

src/domain/LegalFactDownloadMetadataRecord.ts
src/domain/__tests__/data.ts
src/domain/checks/DownloadRecordChecks.ts
src/domain/checks/LegalFactDownloadMetadataChecks.ts
src/domain/checks/__tests__/LegalFactDownloadMetadataChecks.test.ts
src/domain/checks/tcSend03.ts

Verify the legal fact has been downloaded.
Add a check to verify that

[VL-173] - Check legal fact download

---

src/domain/GetNotificationPriceRecord.ts
src/domain/__tests__/data.ts
src/domain/checks/GetNotificationPriceRecordChecks.ts
src/domain/checks/NewNotificationRequestRecordChecks.ts
src/domain/checks/__tests__/ConsumeEventStreamRecordChecks.test.ts
src/domain/checks/__tests__/GetNotificationPriceRecordChecks.test.ts
src/domain/checks/__tests__/NewNotificationRequestRecordChecks.test.ts
src/domain/checks/report.ts
src/domain/checks/tcPayment01.ts

Add a new check (`TC-PAYMENT-01`)
TODO

VL-168 Add the structure for the TC-PAYMENT-01 check

---

src/adapters/http/application.ts
src/adapters/http/getStreamById/router.ts
src/domain/GetEventStreamByIdRecord.ts
src/domain/Repository.ts

Add the endpoint that returns the details of a stream given the id.
This is requires, because the e2e testing invoke this endpoint when executing the TC_Send_02 test suite.

[VL-196] - Get stream by id endpoint

---

src/adapters/http/application.ts
src/adapters/http/deleteEventStream/router.ts
src/domain/DeleteStreamRecord.ts
src/domain/Repository.ts
src/domain/types.ts

Add the endpoint that deletes a stream by its id.
This is requires, because the e2e testing invoke this endpoint when executing the TC_Send_02 test suite.

[VL-198] - Delete stream endpoint

---

src/adapters/http/uploadToS3/router.ts
src/useCases/PersistRecord.ts

Before this PR, the value returned as `x-amz-version-id` was wrong. After this PR the value returned is correct.
Manual test

VL-246 Fix the value of 'x-amz-version-id'

---

src/domain/checks/tcSend01bis.ts

The checks about payment on tc-send-01bis are incorrect because no payment is expected in this context.
Manually

VL-247 Remove useless checks from tc-send-01bis

---

src/domain/__tests__/data.ts
src/domain/checks/LegalFactDownloadMetadataChecks.ts

Improve the check that verifies if a legal fact has been downloaded
Both manually and with unit tests, using red green refactor

[VL-245] - Verify legalFactId contains proper id

---

src/domain/GetNotificationDocumentMetadataRecord.ts

Use array position as docIdx
PN use the position of the document as docIdx

[VL-242] - Use array position as docIdx

---

openapi/bundled-api-external-b2b-pa-v1.yaml
openapi/how-to-generate-the-bundled-openapi-definition.md
package.json
src/domain/ConsumeEventStreamRecord.ts
src/domain/GetNotificationDetailRecord.ts
src/domain/GetNotificationDocumentMetadataRecord.ts
src/domain/GetNotificationPriceRecord.ts
src/domain/GetPaymentNotificationMetadataRecord.ts
src/domain/LegalFactDownloadMetadataRecord.ts
src/domain/ListEventStreamRecord.ts
src/domain/Notification.ts
src/domain/Snapshot.ts
src/domain/TimelineElement.ts
src/domain/__tests__/GetNotificationDetailRecord.test.ts
src/domain/__tests__/ListEventStreamRecord.test.ts
src/domain/__tests__/data.ts
src/domain/checks/ConsumeEventStreamRecordChecks.ts
src/domain/types.ts

- Update open-api to latest version
- Remove `notificationRequestId` from [retrieveSentNotification](https://petstore.swagger.io/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fpagopa%2Fpn-delivery%2Fdevelop%2Fdocs%2Fopenapi%2Fapi-external-b2b-pa.yaml#/SenderReadB2B/retrieveSentNotification)
- Remove `activationDate`, `filterValues `, and `eventType` from [listEventStreams](https://petstore.swagger.io/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fpagopa%2Fpn-delivery-push%2Fdevelop%2Fdocs%2Fopenapi%2Fapi-external-b2b-webhook.yaml#/Streams/listEventStreams)
- Add missing properties to [consumeEventStream](https://petstore.swagger.io/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fpagopa%2Fpn-delivery-push%2Fdevelop%2Fdocs%2Fopenapi%2Fapi-external-b2b-webhook.yaml#/Events/consumeEventStream) …

VL-270 - Update open-api and remove useless fields from response of stream list and notification detail

---

src/domain/checks/LegalFactDownloadMetadataChecks.ts
src/domain/checks/__tests__/LegalFactDownloadMetadataChecks.test.ts

Update `getLegalFactDownloadMetadataRecord` check
`getLegalFactDownloadMetadataRecord` check can't be turned from false to true.
Unit Tests.

VL-275 Legal facts checks

---

package-lock.json
package.json
src/adapters/http/checklist/router.ts
tsconfig.json

Release version 0.14.8

---

.vscode/launch.json
package-lock.json
package.json
src/adapters/http/Handler.ts
src/adapters/http/application.ts
src/adapters/http/checklist/router.ts
src/adapters/http/deleteEventStream/router.ts
src/adapters/http/getRequestResponse/__tests__/router.test.ts
src/adapters/http/getRequestResponse/router.ts
src/adapters/http/requestsLogger/__test__/middleware.test.ts
src/adapters/http/requestsLogger/middleware.ts
src/adapters/http/updateEventStream/router.ts
src/adapters/inMemory/__tests__/index.test.ts
src/adapters/inMemory/index.ts
src/domain/DeleteStreamRecord.ts
src/domain/Repository.ts
src/domain/RequestResponse.ts
src/domain/RequestResponseElement.ts
src/domain/RequestResponseRecord.ts
src/domain/UpdateStreamRecord.ts
src/domain/__tests__/DeleteStreamRecord.test.ts
src/domain/__tests__/RequestResponseRecord.test.ts
src/domain/__tests__/UpdateStreamRecord.test.ts
src/domain/__tests__/data.ts
src/useCases/PersistRecord.ts
tsconfig.json

Release version 0.14.9
